name: todo

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  intl: ^0.20.1
  hive: ^2.2.3
  hive_flutter: 1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: asset/Poppins-SemiBold.ttf

    - family: Poppins
      fonts:
        - asset: asset/Poppins-Regular.ttf
